### ISSUE TITLE
Hash Interface

### ISSUE THREAD

**Issue by glaslos** [glaslos/ssdeep#11]
Create an [Hash](https://golang.org/pkg/hash/#Hash) compatible object for ongoing hashing.

**Comment by davidt99** [comment]
Although the Hash interface doesn't "fit" ssdeep so well - it has some functions that aren't really relevant for ssdeep (`BlockSize` for example), it's common in other language (i'm coming from python) that a hash function satisfy the language standard for hasing.

**Comment by glaslos** [comment]
Generally a good idea. But how do you implement that you always have to provide the file size first? `SetSize(int)` or a `Init()`? `io.Writer` kinda makes only sense if your hash can be updated without prior knowledge about the final amount of data.

**Comment by davidt99** [comment]
Are we looking at the same `Writer`? I'm looking at [this](https://golang.org/pkg/io/#Writer) and the interface has only `Write` method.
I already implemented the hash interface, just need to make sure everything is working and push it.

**Comment by glaslos** [comment]
Okay, looking forward how you have done this :)

**Comment by glaslos** [comment]
We decided to not go for the Hash interface. See comments in the PR and more specific here: https://github.com/glaslos/ssdeep/pull/15#issuecomment-354755865
