### ISSUE TITLE
Integrity testing

### ISSUE THREAD

**Issue by glaslos** [glaslos/ssdeep#13]
Add more tests to verify the implementation matches the reference implementation.

**Comment by davidt99** [comment]
I'll create a script that scans a directory and compare go ssdeep and the reference ssdeep and compare the result. I'll run the script on my machine and if everything is ok, we can close this issue.

**Comment by LordNoteworthy** [comment]
Maybe this should also run on your TravisCI tests.

**Comment by davidt99** [comment]
I was thinking to test it in a docker container with both implementations, I'll try to get to it this week.
