### ISSUE TITLE
Verify Distance Calculation

### ISSUE THREAD

**Issue by glaslos** [glaslos/ssdeep#14]
Verify that the distance function is correct - looking at the code, it seems that the implementation is incomplete.

**Comment by glaslos** [comment]
This is still open. @davidt99 did you had some time to look into this?

**Comment by davidt99** [comment]
Sorry, I was away from go for a while.
I checked the [TODO](https://github.com/glaslos/ssdeep/blob/master/score.go#L73) in `score.go` and it's  correct, the original implementation has [the same logic](https://github.com/ssdeep-project/ssdeep/blob/master/fuzzy.c#L839), but I couldn't reproduce this in a test.
If you calculate it, the block size needs to be really small so the condition will be true...
I'll push what I did in a couple hours.
