### ISSUE TITLE
Can you set minFileSize smaller than 4096

### ISSUE THREAD

**Issue by rexzheng324-c** [glaslos/ssdeep#25]
Why is 4096? If the file size is larger than 4096, the block size may be large than 48.

**Comment by glaslos** [comment]
What is the behavior of the reference implementation?
SSDEEP requires a certain file size to create a meaningful hash.

**Comment by dharnitski** [comment]
Smaller strings are supported in other implementations. It would be nice if we have features parity. It could be optional if necessary. I am currently working to migrate some code from Python to Go and this is a problem for my project (not arguing about the meaningfulness of that hash).

This is a test case string  - `Also called fuzzy hashes, Ctph can match inputs that have homologies.`

Python and the command line in Mac return the same hash for it.
https://pypi.org/project/ssdeep/

`3:AXGBicFlgVNhBGcL6wCrFQEv:AXGHsNhxLsr2C`

**Comment by rexzheng324-c** [comment]
> Smaller strings are supported in other implementations. It would be nice if we have features parity. It could be optional if necessary. I am currently working to migrate some code from Python to Go and this is a problem for my project (not arguing about the meaningfulness of that hash).
> 
> This is a test case string - `Also called fuzzy hashes, Ctph can match inputs that have homologies.`
> 
> Python and the command line in Mac return the same hash for it. https://pypi.org/project/ssdeep/
> 
> `3:AXGBicFlgVNhBGcL6wCrFQEv:AXGHsNhxLsr2C`

The same reason. So I drop the limitation of file size and the hash is the same as Python version and the command line in Mac.By the way, the Python version is relatively hard to install.

**Comment by glaslos** [comment]
There is the `--force` flag if you use the binary or you can set `ssdeep.Force` to true to ignore the minimum file length requirement. I hope this solve your issue.

**Comment by glaslos** [comment]
@rexzheng324-c did this resolve your issue?

**Comment by rexzheng324-c** [comment]
thx
